#ifndef FFP_h__
#define FFP_h__

#include "LString.h"

#define FFP_VERTEXELEMENT_POSITION (STR("FFP_POSITION"))
#define FFP_VERTEXELEMENT_TEXCOORD (STR("FFP_TEXCOORD"))
#define FFP_VERTEXELEMENT_NORMAL (STR("FFP_NORMAL"))
#define FFP_VERTEXELEMENT_VERTEXCOLOR (STR("FFP_VERTEXCOLOR"))


#endif // FFP_h__
